### ISSUE TITLE
ios图片上传手机拍摄的照片会有问题

### ISSUE THREAD

**Issue by wcnsj** [Q956164483/vue-image-cropper#2]
ios图片上传手机拍摄的照片会有问题
我选择是1比1的，截图的时候左边会多出一条黑边

**Comment by wploey** [comment]
显示裁剪界面的这个方法, 在显示图片前没有旋转图片, 导致了截取时宽高不相等时截取出现黑边

**Comment by Simonsms** [comment]
安卓端还会出现 一个边框

**Comment by Simonsms** [comment]
> ios图片上传手机拍摄的照片会有问题
> 我选择是1比1的，截图的时候左边会多出一条黑边

**Comment by Q956164483** [comment]
已经解决了，之前一直在码云，忘了更新，不好意思啊
